
class Constants{

  static final String generatedCodeWarning =
      'Autogenerated from uniAPI, do not edit directly.';

  static final String generatedClassWarning =
      'Autogenerated class from uniAPI, do not edit directly.';

  static final String generatedInterfaceWarning =
      'Autogenerated interface from uniAPI, do not edit directly.';

  static final String channelPrefix = "com.yc.channel";
}
