<template><div><h1 id="config" tabindex="-1"><a class="header-anchor" href="#config"><span>Config</span></a></h1>
<h2 id="hostname" tabindex="-1"><a class="header-anchor" href="#hostname"><span>hostname</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>Required: Yes</p>
</li>
<li>
<p>Details:</p>
<p>The domain name where the current site is deployed, the plugin needs this option to work.</p>
</li>
</ul>
<h2 id="extraurls" tabindex="-1"><a class="header-anchor" href="#extraurls"><span>extraUrls</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string[]</code></p>
</li>
<li>
<p>Details:</p>
<p>Extra link to be included.</p>
<p>If you have some links not including in VuePress Router (normally in public directory or generated by other tools directly), you may need this option.</p>
</li>
<li>
<p>Example: <code v-pre>['/about.html', '/api/']</code></p>
</li>
</ul>
<h2 id="excludepaths" tabindex="-1"><a class="header-anchor" href="#excludepaths"><span>excludePaths</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string[]</code></p>
</li>
<li>
<p>Default: <code v-pre>['/404.html']</code></p>
</li>
<li>
<p>Details:</p>
<p>Urls excluding from sitemap, starting with absolute path.</p>
<p>By default, all the urls generated by VuePress (excluding 404 page) will be added into sitemap.</p>
</li>
</ul>
<h2 id="devserver" tabindex="-1"><a class="header-anchor" href="#devserver"><span>devServer</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>boolean</code></p>
</li>
<li>
<p>Default: <code v-pre>false</code></p>
</li>
<li>
<p>Details:</p>
<p>Whether enabled in devServer.</p>
</li>
</ul>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>For performance reasons, we do not provide hot reload. Reboot your devServer to sync your changes.</p>
</div>
<h2 id="devhostname" tabindex="-1"><a class="header-anchor" href="#devhostname"><span>devHostname</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>Default: <code v-pre>&quot;http://localhost:${port}&quot;</code></p>
</li>
<li>
<p>Details:</p>
<p>Hostname to use in devServer</p>
</li>
</ul>
<h2 id="sitemapfilename" tabindex="-1"><a class="header-anchor" href="#sitemapfilename"><span>sitemapFilename</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>Default value: <code v-pre>&quot;sitemap.xml&quot;</code></p>
</li>
<li>
<p>Details:</p>
<p>The output filename, relative to output directory.</p>
</li>
</ul>
<h2 id="sitemapxslfilename" tabindex="-1"><a class="header-anchor" href="#sitemapxslfilename"><span>sitemapXSLFilename</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>Default value: <code v-pre>&quot;sitemap.xsl&quot;</code></p>
</li>
<li>
<p>Details:</p>
<p>Output xsl filename, relative to dest folder.</p>
</li>
</ul>
<h2 id="sitemapxsltemplate" tabindex="-1"><a class="header-anchor" href="#sitemapxsltemplate"><span>sitemapXSLTemplate</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>Default value: <code v-pre>&quot;@vuepress/plugin-sitemap/templates/sitemap.xsl&quot;</code></p>
</li>
<li>
<p>Details:</p>
<p>XSL content used as template.</p>
</li>
</ul>
<h2 id="changefreq" tabindex="-1"><a class="header-anchor" href="#changefreq"><span>changefreq</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>&quot;always&quot; | &quot;hourly&quot; | &quot;daily&quot; | &quot;weekly&quot; |&quot;monthly&quot; | &quot;yearly&quot; | &quot;never&quot;</code></p>
</li>
<li>
<p>Default value: <code v-pre>&quot;daily&quot;</code></p>
</li>
<li>
<p>Details:</p>
<p>Page default update frequency, will be overridden by <RouteLink to="/plugins/seo/sitemap/frontmatter.html#sitemap-changefreq">sitemap.changefreq</RouteLink> in Frontmatter.</p>
</li>
</ul>
<h2 id="priority" tabindex="-1"><a class="header-anchor" href="#priority"><span>priority</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>number</code></p>
</li>
<li>
<p>Default: <code v-pre>0.5</code></p>
</li>
<li>
<p>Details:</p>
<p>Page priority, from <code v-pre>0</code> to <code v-pre>1</code>.</p>
</li>
</ul>
<h2 id="modifytimegetter" tabindex="-1"><a class="header-anchor" href="#modifytimegetter"><span>modifyTimeGetter</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>(page: Page, app: App) =&gt; string</code></p>
</li>
<li>
<p>Details:</p>
<p>Last modify time getter. By default, the plugin will use the timestamp generated by git plugin.</p>
</li>
</ul>
</div></template>


