<template><div><h1 id="guide" tabindex="-1"><a class="header-anchor" href="#guide"><span>Guide</span></a></h1>
<p>This plugin will automatically generate a Sitemap for your site. To let this plugin work, you need to pass the deployed domain name to the <code v-pre>hostname</code> option of the plugin. If you want to preview in devServer, set <code v-pre>devServer</code> options.</p>
<p>The plugin will automatically generate the last update time of the page based on the Git timestamp of the page, and will also declare the alternative links of the page in other languages according to the locales' config.</p>
<h2 id="control-sitemap-link" tabindex="-1"><a class="header-anchor" href="#control-sitemap-link"><span>Control Sitemap Link</span></a></h2>
<p>By default, all site links except 404 page will be added to the Sitemap.</p>
<p>To add other pages to the Sitemap outside the VuePress project page, please turn them into an array and pass to the <code v-pre>extraUrls</code> plugin option.</p>
<p>If you don't want certain pages to appear in the sitemap, you can turn their paths into an array and pass to the <code v-pre>excludePaths</code> plugin option, or set <code v-pre>sitemap</code> to <code v-pre>false</code> in the frontmatter of the corresponding page.</p>
<h2 id="output-location" tabindex="-1"><a class="header-anchor" href="#output-location"><span>Output Location</span></a></h2>
<p>You can also control the output link through the <code v-pre>sitemapFilename</code> option of the plugin, the link is relative to output directory. By default, the plugin will use <code v-pre>sitemap.xml</code>.</p>
<h2 id="change-frequency" tabindex="-1"><a class="header-anchor" href="#change-frequency"><span>Change Frequency</span></a></h2>
<p>The default update cycle of the page is <code v-pre>daily</code> (every day). To modify the entire page cycle, please set <code v-pre>changefreq</code> in the plugin options. You can also set <code v-pre>sitemap.changefreq</code> in the frontmatter of the page. Note that page has a higher priority.</p>
<p>The legal frequencies are:</p>
<ul>
<li><code v-pre>&quot;always&quot;</code></li>
<li><code v-pre>&quot;hourly&quot;</code></li>
<li><code v-pre>&quot;daily&quot;</code></li>
<li><code v-pre>&quot;weekly&quot;</code></li>
<li><code v-pre>&quot;monthly&quot;</code></li>
<li><code v-pre>&quot;yearly&quot;</code></li>
<li><code v-pre>&quot;never&quot;</code></li>
</ul>
<h2 id="priority" tabindex="-1"><a class="header-anchor" href="#priority"><span>Priority</span></a></h2>
<p>You can set <code v-pre>priority</code> in the plugin to provide a default value. At the same time you can set the priority for each page through <code v-pre>sitemap.priority</code> in frontmatter. Acceptable values are floating point numbers from <code v-pre>0</code> to <code v-pre>1</code>.</p>
<h2 id="modify-time" tabindex="-1"><a class="header-anchor" href="#modify-time"><span>Modify Time</span></a></h2>
<p>You can use option <code v-pre>modifyTimeGetter</code> to return a time in ISO string format, which is generated by the Git plugin by default.</p>
<p>The following is an example based on the last modification time of a file.</p>
<div class="language-typescript" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre class="language-typescript"><code><span class="line"><span class="token comment">// Based on file last modified time</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">   <span class="token function-variable function">modifyTimeGetter</span><span class="token operator">:</span> <span class="token punctuation">(</span>page<span class="token punctuation">,</span> app<span class="token punctuation">)</span> <span class="token operator">=></span></span>
<span class="line">     fs<span class="token punctuation">.</span><span class="token function">statSync</span><span class="token punctuation">(</span>app<span class="token punctuation">.</span>dir<span class="token punctuation">.</span><span class="token function">source</span><span class="token punctuation">(</span>page<span class="token punctuation">.</span>filePathRelative<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>mtime<span class="token punctuation">.</span><span class="token function">toISOString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
</div><h2 id="sitemap-intro" tabindex="-1"><a class="header-anchor" href="#sitemap-intro"><span>Sitemap Intro</span></a></h2>
<p>Sitemaps provide SEO (Search Engine Optimization):</p>
<ul>
<li>Provide search engine spiders with links of the entire site;</li>
<li>Provide some links for search engine spiders to dynamic pages or pages that are difficult to reach by other methods;</li>
<li>If a visitor attempts to access a URL that does not exist within the site's domain, the visitor will be directed to a &quot;file not found&quot; error page, and the sitemap can be used as a navigation page.</li>
</ul>
<p>A sitemap enhances SEO by making all pages findable.</p>
<p>Most search engines only follow a limited number of links within a page, so when the site is very large, a sitemap becomes essential to make everything on the site accessible to search engines and visitors.</p>
<p>Sitemaps is a protocol for site administrators to publish pages that can be crawled on a site to search engine spiders. The content of sitemap files must follow the definition in XML format. Each URL can contain the update period and last update time, the priority of the URL across the site. This allows search engines to crawl site content better and more efficiently.</p>
<div class="custom-container warning"><p class="custom-container-title">Together with robots.txt</p>
<p>Sitemap is basically used by search engines, when using this plugin, you'd better ensure that you have a valid <code v-pre>robots.txt</code> in the <code v-pre>.vuepress/public</code> directory to allow search engines spiders to visit your site. The simplest robots.txt is as follows (allow all search engines to access all paths)</p>
<div class="language-txt" data-highlighter="prismjs" data-ext="txt" data-title="txt"><pre v-pre class="language-txt"><code><span class="line">User-agent: *</span>
<span class="line"></span>
<span class="line">Allow: /</span>
<span class="line"></span></code></pre>
</div></div>
</div></template>


