<template><div><h1 id="channel-config" tabindex="-1"><a class="header-anchor" href="#channel-config"><span>Channel Config</span></a></h1>
<p>The channel plugin option is used to config the feed channel.</p>
<h2 id="channel-title" tabindex="-1"><a class="header-anchor" href="#channel-title"><span>channel.title</span></a></h2>
<ul>
<li>Type: <code v-pre>string</code></li>
<li>Default: <code v-pre>SiteConfig.title</code></li>
</ul>
<p>Channel title</p>
<h2 id="channel-link" tabindex="-1"><a class="header-anchor" href="#channel-link"><span>channel.link</span></a></h2>
<ul>
<li>Type: <code v-pre>string</code></li>
<li>Default: Deployment link (generated by <code v-pre>options.hostname</code> and <code v-pre>context.base</code>)</li>
</ul>
<p>Channel address</p>
<h2 id="channel-description" tabindex="-1"><a class="header-anchor" href="#channel-description"><span>channel.description</span></a></h2>
<ul>
<li>Type: <code v-pre>string</code></li>
<li>Default: <code v-pre>SiteConfig.description</code></li>
</ul>
<p>Channel description</p>
<h2 id="channel-language" tabindex="-1"><a class="header-anchor" href="#channel-language"><span>channel.language</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>Default:</p>
<ul>
<li><code v-pre>siteConfig.locales['/'].lang</code></li>
<li>If the above is not provided, fall back to <code v-pre>&quot;en-US&quot;</code></li>
</ul>
</li>
</ul>
<p>The language of the channel</p>
<h2 id="channel-copyright" tabindex="-1"><a class="header-anchor" href="#channel-copyright"><span>channel.copyright</span></a></h2>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>Default:</p>
<ul>
<li>Try to read the <code v-pre>author.name</code> in channel options, and fall back to <code v-pre>Copyright by $author</code></li>
</ul>
</li>
<li>
<p>Recommended to set manually: <strong>Yes</strong></p>
</li>
</ul>
<p>Channel copyright information</p>
<h2 id="channel-pubdate" tabindex="-1"><a class="header-anchor" href="#channel-pubdate"><span>channel.pubDate</span></a></h2>
<ul>
<li>Type: <code v-pre>string</code> (must be a valid Date ISOString)</li>
<li>Default: time when the plugin is called each time</li>
<li>Recommended to set manually: <strong>Yes</strong></li>
</ul>
<p>Publish date of the Channel</p>
<h2 id="channel-lastupdated" tabindex="-1"><a class="header-anchor" href="#channel-lastupdated"><span>channel.lastUpdated</span></a></h2>
<ul>
<li>Type: <code v-pre>string</code> (must be a valid Date ISOString)</li>
<li>Default: time when the plugin is called each time</li>
</ul>
<p>Last update time of channel content</p>
<h2 id="channel-ttl" tabindex="-1"><a class="header-anchor" href="#channel-ttl"><span>channel.ttl</span></a></h2>
<ul>
<li>Type: <code v-pre>number</code></li>
<li>Recommended to set manually: <strong>Yes</strong></li>
</ul>
<p>The effective time of the content. It's the time to keep the cache after request without making new requests.</p>
<h2 id="channel-image" tabindex="-1"><a class="header-anchor" href="#channel-image"><span>channel.image</span></a></h2>
<ul>
<li>Type: <code v-pre>string</code></li>
<li>Recommended to set manually: <strong>Yes</strong></li>
</ul>
<p>A picture presenting the channel. A square picture with a size not smaller than 512×512 is recommended.</p>
<h2 id="channel-icon" tabindex="-1"><a class="header-anchor" href="#channel-icon"><span>channel.icon</span></a></h2>
<ul>
<li>Type: <code v-pre>string</code></li>
<li>Recommended to set manually: <strong>Yes</strong></li>
</ul>
<p>An icon representing a channel, a square picture, with not less than 128×128 in size, and transparent background color is recommended.</p>
<h2 id="channel-author" tabindex="-1"><a class="header-anchor" href="#channel-author"><span>channel.author</span></a></h2>
<ul>
<li>Type: <code v-pre>FeedAuthor</code></li>
<li>Recommended to set manually: <strong>Yes</strong></li>
</ul>
<p>The author of the channel.</p>
<details class="custom-container details"><summary>FeedAuthor format</summary>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre class="language-typescript"><code><span class="line"><span class="token keyword">interface</span> <span class="token class-name">FeedAuthor</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token doc-comment comment">/** Author name */</span></span>
<span class="line">  name<span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line">  <span class="token doc-comment comment">/** Author's email */</span></span>
<span class="line">  email<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line">  <span class="token doc-comment comment">/** Author's site */</span></span>
<span class="line">  url<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author's avatar address</span>
<span class="line">   *</span>
<span class="line">   * Square, preferably not less than 128×128 with transparent background</span>
<span class="line">   */</span></span>
<span class="line">  avatar<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="channel-hub" tabindex="-1"><a class="header-anchor" href="#channel-hub"><span>channel.hub</span></a></h2>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>Link to Websub. Websub requires a server backend, which is inconsistent with VuePress, so ignore it if there is no special need.</p>
<div class="custom-container tip"><p class="custom-container-title">WebSub</p>
<p>For details, see <a href="https://w3c.github.io/websub/#subscription-migration" target="_blank" rel="noopener noreferrer">Websub</a>.</p>
</div>
</details>
</div></template>


