<template><div><h1 id="frontmatter-config" tabindex="-1"><a class="header-anchor" href="#frontmatter-config"><span>Frontmatter Config</span></a></h1>
<p>You can control each feed item generation by setting page frontmatter.</p>
<h2 id="additions-and-removals" tabindex="-1"><a class="header-anchor" href="#additions-and-removals"><span>Additions and Removals</span></a></h2>
<p>By default, all articles are added to the feed stream. Set <code v-pre>feed: false</code> in frontmatter to remove a page from feed.</p>
<h2 id="frontmatter-information" tabindex="-1"><a class="header-anchor" href="#frontmatter-information"><span>Frontmatter Information</span></a></h2>
<h3 id="title" tabindex="-1"><a class="header-anchor" href="#title"><span>title</span></a></h3>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>Automatically generated by VuePress, defaults to the h1 content of the page</p>
<h3 id="description" tabindex="-1"><a class="header-anchor" href="#description"><span>description</span></a></h3>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>Description of the page</p>
<h3 id="date" tabindex="-1"><a class="header-anchor" href="#date"><span>date</span></a></h3>
<ul>
<li>Type: <code v-pre>Date</code></li>
</ul>
<p>Date when the page was published</p>
<h3 id="article" tabindex="-1"><a class="header-anchor" href="#article"><span>article</span></a></h3>
<ul>
<li>Type: <code v-pre>boolean</code></li>
</ul>
<p>Whether the page is an article</p>
<blockquote>
<p>If this is set to <code v-pre>false</code>, the page will not be included in the final feed.</p>
</blockquote>
<h3 id="copyright" tabindex="-1"><a class="header-anchor" href="#copyright"><span>copyright</span></a></h3>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>Page copyright information</p>
<h3 id="cover-image-banner" tabindex="-1"><a class="header-anchor" href="#cover-image-banner"><span>cover / image / banner</span></a></h3>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>Image used as page cover , should be full link or absolute link.</p>
<h2 id="frontmatter-options" tabindex="-1"><a class="header-anchor" href="#frontmatter-options"><span>Frontmatter Options</span></a></h2>
<h3 id="feed-title" tabindex="-1"><a class="header-anchor" href="#feed-title"><span>feed.title</span></a></h3>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>The title of the feed item</p>
<h3 id="feed-description" tabindex="-1"><a class="header-anchor" href="#feed-description"><span>feed.description</span></a></h3>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>Description of the feed item</p>
<h3 id="feed-content" tabindex="-1"><a class="header-anchor" href="#feed-content"><span>feed.content</span></a></h3>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>The content of the feed item</p>
<h3 id="feed-author" tabindex="-1"><a class="header-anchor" href="#feed-author"><span>feed.author</span></a></h3>
<ul>
<li>Type: <code v-pre>FeedAuthor[] | FeedAuthor</code></li>
</ul>
<p>The author of the feed item</p>
<details class="custom-container details"><summary>FeedAuthor format</summary>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre class="language-typescript"><code><span class="line"><span class="token keyword">interface</span> <span class="token class-name">FeedAuthor</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author name</span>
<span class="line">   */</span></span>
<span class="line">  name<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author email</span>
<span class="line">   */</span></span>
<span class="line">  email<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author site</span>
<span class="line">   *</span>
<span class="line">   * <span class="token keyword">@description</span> json format only</span>
<span class="line">   */</span></span>
<span class="line">  url<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author avatar</span>
<span class="line">   *</span>
<span class="line">   * <span class="token keyword">@description</span> json format only</span>
<span class="line">   */</span></span>
<span class="line">  avatar<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></details>
<h3 id="feed-contributor" tabindex="-1"><a class="header-anchor" href="#feed-contributor"><span>feed.contributor</span></a></h3>
<ul>
<li>Type: <code v-pre>FeedContributor[] | FeedContributor</code></li>
</ul>
<p>Contributors to feed item</p>
<details class="custom-container details"><summary>FeedContributor format</summary>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre class="language-typescript"><code><span class="line"><span class="token keyword">interface</span> <span class="token class-name">FeedContributor</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author name</span>
<span class="line">   */</span></span>
<span class="line">  name<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author email</span>
<span class="line">   */</span></span>
<span class="line">  email<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author site</span>
<span class="line">   *</span>
<span class="line">   * <span class="token keyword">@description</span> json format only</span>
<span class="line">   */</span></span>
<span class="line">  url<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"></span>
<span class="line">  <span class="token doc-comment comment">/**</span>
<span class="line">   * Author avatar</span>
<span class="line">   *</span>
<span class="line">   * <span class="token keyword">@description</span> json format only</span>
<span class="line">   */</span></span>
<span class="line">  avatar<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></details>
<h3 id="feed-guid" tabindex="-1"><a class="header-anchor" href="#feed-guid"><span>feed.guid</span></a></h3>
<ul>
<li>Type: <code v-pre>string</code></li>
</ul>
<p>The identifier of feed item, used to identify the feed item.</p>
<div class="custom-container tip"><p class="custom-container-title">You should ensure every feed has a unique guid.</p>
</div>
</div></template>


