const padZero = (num, length = 2) => num.toString().padStart(length, '0');
const getFullYear = (date) => padZero(date.getFullYear(), 4);
const getMonth = (date) => padZero(date.getMonth() + 1);
const getDate = (date) => padZero(date.getDate());
const getHours = (date) => padZero(date.getHours());
const getMinutes = (date) => padZero(date.getMinutes());
const getSeconds = (date) => padZero(date.getSeconds());
export const getDateString = (date) => `${getFullYear(date)}-${getMonth(date)}-${getDate(date)}`;
export const getTimeString = (date) => `${getHours(date)}:${getMinutes(date)}:${getSeconds(date)}`;
export const getFullDateString = (date) => `${getDateString(date)} ${getTimeString(date)}`;
