const String generatedCodeWarning =
    'Autogenerated from uniAPI, do not edit directly.';

const String generatedClassWarning =
    'Autogenerated class from uniAPI, do not edit directly.';

const String generatedInterfaceWarning =
    'Autogenerated interface from uniAPI, do not edit directly.';

const String channelPrefix = "com.didi.rlab.uni_api";